import {
  HiHome,
  HiSpeakerphone,
  HiUserGroup,
  HiUsers,
  HiTemplate,
  HiChartBar,
  HiChatAlt2,
  HiIdentification,
  HiCloud,
  HiDocumentReport,
  HiCog,
  HiLockClosed,
  HiLogout,
  HiViewGrid,
  HiChatAlt,
  HiUserCircle,
  HiPresentationChartBar,
  HiMenu ,
  HiCollection,
  HiClipboardList ,
  HiCube,
} from "react-icons/hi";

export const sidebarItems = [
    {
      href: '/Dashboard',
      icon: <HiHome className="text-xl" />,
      text: 'Dashboard',
      module: 1,
      submenu: [],
    },
    {
      href: '/Campaigns/CampaignsList',
      icon: <HiSpeakerphone className="text-xl" />,
      text: 'Campaigns',
      module: 1,
      submenu: [],
    },
    {
      href: '/Groups/GroupList',
      icon: <HiUserGroup className="text-xl" />,
      text: 'Groups',
      module: 1,
      submenu: [],
    },
    {
      href: '/Contacts/ContactList',
      icon: <HiUsers className="text-xl" />,
      text: 'Contacts',
      module: 1,
      submenu: [],
    },
    {
      href: '/Agents/AgentsList',
      icon: <HiUserCircle className="text-xl" />,
      text: 'Agents',
      module: 1,
      submenu: [],
    },
    {
      href: '/Templates/TemplatesList',
      icon: <HiTemplate className="text-xl" />,
      text: 'Templates',
      module: 1,
      submenu: [],
    },
    {
      href: '/TemplateInsightDetails',
      icon: <HiChartBar className="text-xl" />,
      text: 'Template Insight',
      module: 1,
      submenu: [],
    },
    {
      href: '/InteractiveTemplates/InteractiveList',
      icon: <HiCollection className="text-xl" />,
      text: 'Interactive Templates',
      module: 1,
      submenu: [],
    },
    {
      href: '/Flows/FlowList',
      icon: <HiCube className="text-xl" />,
      text: 'Flows',
      module: 1,
      submenu: [],
    },
    // {
    //   href: '/TemplateVisualisation',
    //   icon: 'ti-eye', 
    //   text: 'Template Visualisation',
    //   module: 1,
    //   submenu: [],
    // },
    {
      href: '/Clients/ClientsList',
      icon: <HiUsers className="text-xl" />,
      text: 'Clients',
      module: 1,
      submenu: [],
    },
    {
      href: '/Chats/ChatsList',
      icon: <HiChatAlt2 className="text-xl" />,
      text: 'Chats',
      module: 1,
      submenu: [],
    },
    {
      href: '/SenderNames/SenderNamelist',
      icon: <HiIdentification className="text-xl" />,
      text: 'Sender Names',
      module: 1,
      submenu: [],
    },
    
    {
      href: '/SenderNamesAdmin/SenderNamelist',
      icon: <HiIdentification className="text-xl" />,
      text: 'Sender Names Admin',
      module: 1,
      submenu: [],
    },
    {
      href: '/Media/MediaList',
      icon: <HiCloud className="text-xl" />,
      text: 'Media',
      module: 1,
      submenu: [],
    },
    {
      href: '/Menu',
      icon: <HiMenu  className="text-xl" />,
      text: 'Menu',
      module: 1,
      submenu: [],
    },
    {
      href: '/Order/OrdersList',
      icon: <HiClipboardList  className="text-xl" />,
      text: 'Order',
      module: 1,
      submenu: [],
    },
    {
      href: '/Enquiry/EnquiryList',
      icon: <HiClipboardList  className="text-xl" />,
      text: 'Enquiry',
      module: 1,
      submenu: [],
    },
    {
      href: '#',
      icon: <HiDocumentReport className="text-xl" />,
      text: 'Reports',
      module: 2,
      submenu: [
        {
          href: '/Reports/MessagesReports',
          text: 'Message Reports',
          icon: <HiClipboardList className="text-lg" />,
        },
        // {
        //   href: '/Reports/MessageSummary',
        //   text: 'Message Summary',
        //   icon: 'ti-clipboard', // Pie chart icon for Message Summary
        // },
        {
          href: '/Reports/ChatsReport',
          text: 'Chat Report',
          icon: <HiChatAlt className="text-lg" />,
        },
        {
          href: '/Reports/AgentReport',
          text: 'Agent Report',
          icon: <HiUserCircle className="text-lg" />,
        },
        {
          href: '/Reports/SurveyReport',
          text: 'Survey Report',
          icon: <HiClipboardList className="text-lg" />,
        },
      ],
    },
    {
      href: '#',
      icon: <HiUserCircle className="text-xl" />,
      text: 'Supervisor',
      module: 2,
      submenu: [
        {
          href: '/Supervisor/SupervisorDashboard',
          text: 'Dashboard',
          icon: <HiViewGrid className="text-lg" />,
        },
        {
          href: '/Supervisor/ChatsMonitor',
          text: 'Chats Monitor',
          icon: <HiChatAlt2 className="text-lg" />,
        },
        {
          href: '/Supervisor/AgentsMonitor',
          text: 'Agents Monitor',
          icon: <HiPresentationChartBar className="text-lg" />,
        },
       
      ],
    },
    {
      href: '/Roles/RolesList',
      icon: <HiCog className="text-xl" />,
      text: 'Roles',
      module: 1,
      submenu: [],
    },
    {
      href: '/Users/UsersList',
      icon: <HiUsers className="text-xl" />,
      text: 'Users',
      module: 1,
      submenu: [],
    },

    {
      href: '/Permissions/PermissionList',
      icon: <HiLockClosed className="text-xl" />,
      text: 'Permissions',
      module: 1,
      submenu: [],
    },
    {
      href: '/Settings/AppSettingList',
      icon: <HiCog className="text-xl" />,
      text: 'Settings',
      module: 1,
      submenu: [],
    },
    {
      href: '/dashboard',
      icon: <HiLogout className="text-xl" />,
      text: 'Logout',
      module: 3,
      submenu: [],
    },
  ];
  
